### ISSUE TITLE
在db沒有文章資料時   隨機文章功能會出錯誤

### ISSUE THREAD

**Issue by hanbz** [laravel-dojo/201412-ncue-workshop-example#1]
在db沒有文章資料時   隨機文章功能會出錯誤

**Comment by shengyou** [comment]
您好！謝謝您的指正！

不過這個範例程式僅是為了配合教學示範使用，許多功能、錯誤處理並不完整。原本的設定是留待給學員自行思考如何改善，所以並不會針對這個錯誤做修正。特此說明，謝謝！
